# Generated by Django 2.2 on 2019-07-23 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lra_reference', models.CharField(max_length=100)),
                ('procedure_number', models.CharField(max_length=50)),
                ('variation_description', models.TextField()),
                ('date_recieived', models.DateField(auto_now_add=True)),
                ('date_pre_submission', models.DateField(blank=True, null=True)),
                ('date_submission', models.DateField(blank=True, null=True)),
                ('date_approval', models.DateField(blank=True, null=True)),
                ('date_internal_approval_completion', models.DateField(blank=True, null=True)),
                ('date_variation_closed', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.PharmaProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date_resubmitted', models.DateField(blank=True, null=True)),
                ('documents_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resubmission_dossiers', to='variationtracker.Dossier')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resubmission_variations', to='variationtracker.Variation')),
            ],
        ),
        migrations.CreateModel(
            name='NationalPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submission', models.DateField(blank=True, null=True)),
                ('finalised_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalphase_dossiers', to='variationtracker.Dossier')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalphase_variations', to='variationtracker.Variation')),
            ],
        ),
        migrations.CreateModel(
            name='InternalApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_workflow_init', models.DateField(blank=True, null=True)),
                ('date_workflow_approved', models.DateField(blank=True, null=True)),
                ('finalised_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internalapproval_dossiers', to='variationtracker.Dossier')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internalapproval_variations', to='variationtracker.Variation')),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_variations', to='variationtracker.Variation'),
        ),
    ]
