# Generated by Django 2.2 on 2019-07-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0002_auto_20190723_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='personnel',
        ),
    ]
