# Generated by Django 2.2 on 2019-07-23 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('variationtracker', '0003_auto_20190723_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variation',
            name='personnel',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_variations', to='variationtracker.Variation'),
        ),
        migrations.AlterField(
            model_name='internalapproval',
            name='finalised_documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internalapproval_dossiers', to='variationtracker.Dossier'),
        ),
        migrations.AlterField(
            model_name='internalapproval',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internalapproval_variations', to='variationtracker.Variation'),
        ),
        migrations.AlterField(
            model_name='nationalphase',
            name='finalised_documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationalphase_dossiers', to='variationtracker.Dossier'),
        ),
        migrations.AlterField(
            model_name='nationalphase',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationalphase_variations', to='variationtracker.Variation'),
        ),
        migrations.AlterField(
            model_name='resubmission',
            name='documents_required',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resubmission_dossiers', to='variationtracker.Dossier'),
        ),
        migrations.AlterField(
            model_name='resubmission',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resubmission_variations', to='variationtracker.Variation'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.PharmaProduct'),
        ),
    ]
