# Generated by Django 2.2 on 2019-07-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0004_auto_20190723_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='initiated_by',
            field=models.CharField(blank=True, choices=[('LRA', 'LRA'), ('GRA', 'GRA'), ('MHRA', 'MHRA'), ('Other', 'Other')], default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_reason',
            field=models.CharField(blank=True, choices=[('Quality', 'Quality'), ('Patient Information', 'Patient Information')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(blank=True, choices=[('IAN', 'IAN'), ('IA', 'IA'), ('IB', 'IB'), ('II', 'II')], default='', max_length=10, null=True),
        ),
    ]
