# Generated by Django 2.2 on 2019-08-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190811_1124'),
        ('variationtracker', '0005_auto_20190723_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ManyToManyField(to='products.PharmaProduct'),
        ),
    ]
