# Generated by Django 2.2 on 2019-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0006_auto_20190812_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_outcome',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('RFI', 'RFI'), ('PVAR', 'PVAR'), ('Rejected', 'Rejected')], default='', max_length=10, null=True),
        ),
    ]
