# Generated by Django 2.2 on 2019-08-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0007_variation_variation_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='procedure_number',
            field=models.CharField(default='Awaiting', max_length=50),
        ),
    ]
