# Generated by Django 2.2 on 2019-08-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0008_auto_20190814_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='procedure_number',
            field=models.CharField(blank=True, default='Awaiting', max_length=50),
        ),
    ]
