# Generated by Django 2.2 on 2019-08-16 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0010_auto_20190814_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Awaiting', 'Awaiting'), ('Approved', 'Approved'), ('RFI/PVAR', 'RFI/PVAR'), ('Rejected', 'Rejected')], default='AWAITING', max_length=10)),
                ('addional_details', models.TextField()),
                ('decision_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalApprovalPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostDecisionPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreSubmissionPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.TextField()),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('CESP', 'CESP'), ('Direct', 'Direct')], default='CESP', max_length=10)),
                ('details', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='internalapproval',
            name='finalised_documents',
        ),
        migrations.RemoveField(
            model_name='internalapproval',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='resubmission',
            name='documents_required',
        ),
        migrations.RemoveField(
            model_name='resubmission',
            name='variation',
        ),
        migrations.RenameField(
            model_name='nationalphase',
            old_name='date_submission',
            new_name='date_completed',
        ),
        migrations.RemoveField(
            model_name='nationalphase',
            name='finalised_documents',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_outcome',
        ),
        migrations.AddField(
            model_name='nationalphase',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationalphase',
            name='details',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nationalphase',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationalphases', to='variationtracker.Variation'),
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
        migrations.DeleteModel(
            name='InternalApproval',
        ),
        migrations.DeleteModel(
            name='ReSubmission',
        ),
        migrations.AddField(
            model_name='submissionphase',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='variationtracker.Variation'),
        ),
        migrations.AddField(
            model_name='presubmissionphase',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presubmissions', to='variationtracker.Variation'),
        ),
        migrations.AddField(
            model_name='postdecisionphase',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postdecisions', to='variationtracker.Variation'),
        ),
        migrations.AddField(
            model_name='internalapprovalphase',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='variationtracker.Variation'),
        ),
        migrations.AddField(
            model_name='decisionphase',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='variationtracker.Variation'),
        ),
    ]
