# Generated by Django 2.2 on 2019-08-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0011_auto_20190816_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionphase',
            name='decision_date',
            field=models.DateField(),
        ),
    ]
