# Generated by Django 2.2 on 2019-08-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0013_variationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalapprovalphase',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='nationalphase',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='postdecisionphase',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='presubmissionphase',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='submissionphase',
            name='variation',
        ),
        migrations.DeleteModel(
            name='DecisionPhase',
        ),
        migrations.DeleteModel(
            name='InternalApprovalPhase',
        ),
        migrations.DeleteModel(
            name='NationalPhase',
        ),
        migrations.DeleteModel(
            name='PostDecisionPhase',
        ),
        migrations.DeleteModel(
            name='PreSubmissionPhase',
        ),
        migrations.DeleteModel(
            name='SubmissionPhase',
        ),
    ]
