# Generated by Django 2.2 on 2019-08-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0014_auto_20190819_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationlog',
            name='decision',
            field=models.CharField(choices=[('Pre-submission Phase', 'Pre-Submission Phase'), ('Submission Phase', 'Submission Phase'), ('Post Submission Phase', 'Post Submission Phase'), ('Internal Approval Phase', 'Internal Approval Phase'), ('National Phase', 'National Phase')], default='PresubmissionPhase', max_length=30),
        ),
    ]
