# Generated by Django 2.2 on 2019-08-19 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0015_auto_20190819_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Pre-submission Phase', 'Pre-Submission Phase'), ('Submission Phase', 'Submission Phase'), ('Post Submission Phase', 'Post Submission Phase'), ('Internal Approval Phase', 'Internal Approval Phase'), ('National Phase', 'National Phase')], default='PresubmissionPhase', max_length=30)),
                ('details', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='variationtracker.Variation')),
            ],
        ),
        migrations.DeleteModel(
            name='VariationLog',
        ),
    ]
