# Generated by Django 2.2 on 2019-08-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0016_auto_20190819_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='date_recieived',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='date_approval',
            new_name='planned_submission_date',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='date_internal_approval_completion',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='date_pre_submission',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='date_submission',
        ),
    ]
