# Generated by Django 2.2 on 2019-08-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0017_auto_20190819_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='initiated_by',
            field=models.CharField(blank=True, choices=[('LRA', 'LRA'), ('GRA', 'GRA'), ('MHRA', 'MHRA'), ('Other', 'Other')], default='GRA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=15, null=True),
        ),
    ]
