# Generated by Django 2.2 on 2019-05-25 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_auto_20190523_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='personnel',
        ),
        migrations.AddField(
            model_name='job',
            name='personnel',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
