# Generated by Django 2.2 on 2019-05-25 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_auto_20190525_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='personnel',
        ),
        migrations.AddField(
            model_name='job',
            name='personnel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
