# Generated by Django 2.2 on 2019-05-26 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20190526_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='personnel',
        ),
        migrations.AddField(
            model_name='job',
            name='personnel',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
