# Generated by Django 2.2 on 2019-06-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20190613_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
