# Generated by Django 2.2 on 2019-06-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20190614_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.Job'),
        ),
    ]
