# Generated by Django 2.2 on 2019-06-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20190615_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.Job'),
        ),
    ]
