# Generated by Django 2.2 on 2019-06-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20190615_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
