# Generated by Django 2.2 on 2019-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
