# Generated by Django 2.2 on 2019-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20190709_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='job',
        ),
        migrations.AddField(
            model_name='objective',
            name='job',
            field=models.ManyToManyField(to='jobs.Job'),
        ),
    ]
