# Generated by Django 2.2 on 2019-07-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20190709_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='job',
        ),
        migrations.AddField(
            model_name='objective',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Job'),
        ),
    ]
