# Generated by Django 2.2 on 2019-07-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_objective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Objective',
            new_name='objective',
        ),
    ]
