# Generated by Django 2.2 on 2019-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20190709_0851'),
        ('comments', '0003_auto_20190709_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='objective',
        ),
        migrations.AddField(
            model_name='comment',
            name='objective',
            field=models.ManyToManyField(to='jobs.Objective'),
        ),
    ]
