# Generated by Django 2.2 on 2019-07-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_objectivecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectiveComment',
        ),
    ]
