# Generated by Django 2.2 on 2019-07-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_delete_objectivecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='objective',
        ),
    ]
