# Generated by Django 2.2 on 2019-07-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('solution_number', models.CharField(max_length=10)),
                ('licence_number', models.CharField(max_length=20)),
                ('licence_holder', models.CharField(max_length=100)),
                ('storage_conditions', models.CharField(max_length=100)),
            ],
        ),
    ]
