# Generated by Django 2.2 on 2019-07-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variationtracker', '0004_auto_20190723_2002'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmaproduct',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='variationtracker.Variation'),
        ),
    ]
