# Generated by Django 2.2 on 2019-08-07 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_pharmaproduct_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaproduct',
            name='licence_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_licence_number', message='No spaces allowed', regex='^[^\\S]+$')]),
        ),
    ]
