# Generated by Django 2.2 on 2019-08-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190809_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmaproduct',
            name='storage_conditions',
        ),
        migrations.AddField(
            model_name='pharmaproduct',
            name='procedure_type',
            field=models.CharField(choices=[('National', 'National'), ('MRP/DCP', 'MRP/DCP'), ('Centralised', 'Centralised')], default='National', max_length=12),
        ),
    ]
